services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kimsoa/jokibo-interior-design-website:latest
    container_name: jokibo-interior-design-website
    ports:
      - "8008:8008"
    restart: unless-stopped
